import './globals.css';
import AppContextProvider from './AppContext';
import Header from '@/app/components/shared/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body>
        <AppContextProvider>
          <main className="min-h-screen bg-background flex flex-col items-center">
            <Header />
            {children}
          </main>
        </AppContextProvider>
      </body>
    </html>

  );
}