import './globals.css';
import AppContextProvider from './AppContext';
import Header from '@/app/components/shared/Header';

import { ToastContainer, Slide } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("RootLayout")
  return (


    <html lang="en">
      <body>
        <AppContextProvider>
          <Header />
          <main className="min-h-screen bg-background flex flex-col items-center pt-0 sm:pt-20">

            {children}
          </main>
          <ToastContainer position="bottom-right" theme="colored" pauseOnFocusLoss={false} toastStyle={{ opacity: 0.9 }} transition={Slide} />
        </AppContextProvider>
      </body>
    </html>

  );
}